name: Minecraft Framework Project

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=MyAdventures --cov-report=xml --capture=tee-sys -vvv -x

      - name: Check coverage file
        run: |
          if [ ! -f coverage.xml ]; then
            echo "coverage.xml no encontrado, revisa pytest"
            exit 1
          fi

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
